#!/bin/bash
###############################################################################
# Bootstrap Script - Create Terraform State Infrastructure
#
# Run this ONCE before the first terraform init/apply.
# Creates:
#   - S3 bucket for Terraform state (versioned, encrypted)
#   - DynamoDB table for state locking (prevents concurrent modifications)
#
# Usage:
#   export AWS_REGION=us-east-1   # or your preferred region
#   bash scripts/bootstrap.sh
###############################################################################

set -euo pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Configuration
REGION="${AWS_REGION:-us-east-1}"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null) || {
    log_error "AWS credentials not configured. Run 'aws configure' first."
    exit 1
}

BUCKET_NAME="agentcore-owasp-tfstate-${ACCOUNT_ID}-${REGION}"
DYNAMO_TABLE="agentcore-owasp-tfstate-lock"

log_info "Bootstrapping Terraform state infrastructure"
log_info "  Account:  ${ACCOUNT_ID}"
log_info "  Region:   ${REGION}"
log_info "  Bucket:   ${BUCKET_NAME}"
log_info "  Lock Table: ${DYNAMO_TABLE}"
echo ""

###############################################################################
# Create S3 Bucket
###############################################################################

if aws s3api head-bucket --bucket "${BUCKET_NAME}" 2>/dev/null; then
    log_info "S3 bucket already exists: ${BUCKET_NAME}"
else
    log_info "Creating S3 bucket: ${BUCKET_NAME}"

    if [ "${REGION}" = "us-east-1" ]; then
        aws s3api create-bucket \
            --bucket "${BUCKET_NAME}" \
            --region "${REGION}"
    else
        aws s3api create-bucket \
            --bucket "${BUCKET_NAME}" \
            --region "${REGION}" \
            --create-bucket-configuration LocationConstraint="${REGION}"
    fi

    # Enable versioning (allows state recovery)
    aws s3api put-bucket-versioning \
        --bucket "${BUCKET_NAME}" \
        --versioning-configuration Status=Enabled

    # Enable server-side encryption
    aws s3api put-bucket-encryption \
        --bucket "${BUCKET_NAME}" \
        --server-side-encryption-configuration '{
            "Rules": [{
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "aws:kms"
                },
                "BucketKeyEnabled": true
            }]
        }'

    # Block all public access
    aws s3api put-public-access-block \
        --bucket "${BUCKET_NAME}" \
        --public-access-block-configuration '{
            "BlockPublicAcls": true,
            "IgnorePublicAcls": true,
            "BlockPublicPolicy": true,
            "RestrictPublicBuckets": true
        }'

    log_info "S3 bucket created and secured"
fi

###############################################################################
# Create DynamoDB Lock Table
###############################################################################

if aws dynamodb describe-table --table-name "${DYNAMO_TABLE}" --region "${REGION}" >/dev/null 2>&1; then
    log_info "DynamoDB table already exists: ${DYNAMO_TABLE}"
else
    log_info "Creating DynamoDB lock table: ${DYNAMO_TABLE}"

    aws dynamodb create-table \
        --table-name "${DYNAMO_TABLE}" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "${REGION}"

    aws dynamodb wait table-exists \
        --table-name "${DYNAMO_TABLE}" \
        --region "${REGION}"

    log_info "DynamoDB lock table created"
fi

###############################################################################
# Generate backend config
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BACKEND_FILE="${PROJECT_DIR}/terraform/backend.hcl"

cat > "${BACKEND_FILE}" <<EOF
# Auto-generated by bootstrap.sh — do not commit this file
bucket         = "${BUCKET_NAME}"
key            = "agentcore-owasp-demo/terraform.tfstate"
region         = "${REGION}"
dynamodb_table = "${DYNAMO_TABLE}"
encrypt        = true
EOF

log_info "Backend config written to: terraform/backend.hcl"

echo ""
log_info "=== Bootstrap Complete ==="
echo ""
echo "Next steps:"
echo "  cd terraform"
echo "  terraform init -backend-config=backend.hcl"
echo "  terraform plan"
echo "  terraform apply"
